version: 0.0
os: linux
files:
 - source: /
   destination: /
hooks:
  Install:
    - location: /bin/app-setup.sh
      timeout: 3600
  ApplicationStart:
    - location: /bin/app-start.sh
      timeout: 3600

